spring:
  application:
    name: mqdemo
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 5000       #连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 50  #连接池最大连接数（使用负值表示没有限制）
        max-wait: 3000  #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 20    #连接池中的最大空闲连接
        min-idle: 2     #连接池中的最小空闲连接
server:
  port: 8088
rocketmq:
  # rocketmq地址
  name-server: localhost:9876
  producer:
    # 必须填写 group
    group: sjy-mq-group
    send-message-timeout: 86400
    compress-message-body-threshold: 4096
    max-message-size: 4194304
    retry-times-when-send-async-failed: 0
    retry-next-server: true
    retry-times-when-send-failed: 2
nettyConfig:
  address: 192.168.137.120
  port: 8090
